export enum ApiPaths {
  GetProgramTypes = 'Parameter/get-program-types',
  GetCampaignDetail = 'Campaign/get',
  CopyCampaign = 'Approve/copy-campaign',
  GetCampaignInfo = 'Approve/view-campaign',
  CampaignDefinitionList = 'Campaign/get-by-filter',
  CampaignDefinitionListGetExcelFile = 'Campaign/get-by-filter-excel',
  CampaignDefinitionAdd = 'Campaign/add',
  CampaignDefinitionUpdate = 'Campaign/update',
  CampaignDefinitionGetInsertForm = 'Campaign/get-insert-form',
  CampaignRulesAdd = 'CampaignRule/add',
  CampaignRulesUpdate = 'CampaignRule/update',
  CampaignRulesGetInsertForm = 'CampaignRule/get-insert-form',
  CampaignRulesGetUpdateForm = 'CampaignRule/get-update-form',
  CampaignTargetsAdd = 'CampaignTarget/add',
  CampaignTargetsUpdate = 'CampaignTarget/update',
  CampaignTargetsGetUpdateForm = 'CampaignTarget/get-update-form',
  CampaignTargetsGetInsertForm = 'CampaignTarget/get-insert-form',
  CampaignGainChannelsGetListByCampaign = 'CampainAchievement/get-list-by-campaign',
  CampaignGainsGetInsertForm = 'CampainAchievement/get-insert-form',
  CampaignGainsAdd = 'CampainAchievement/update',

  CampaignLimitsGetParameterList = 'CampaignTopLimit/get-parameter-list',
  CampaignLimitsGetByFilter = 'CampaignTopLimit/get-by-filter',
  CampaignLimitsListGetExcelFile = 'CampaignTopLimit/get-by-filter-excel',
  CampaignLimitGetInsertForm = 'CampaignTopLimit/get-insert-form',
  GetLimitDetail = 'CampaignTopLimit/get-update-form',
  CopyLimit = 'Approve/copy-top-limit',
  CampaignLimitAdd = 'CampaignTopLimit/add',
  CampaignLimitUpdate = 'CampaignTopLimit/update',

  GetTargetViewTypes = 'Parameter/get-target-views',
  GetTargetSources = 'Parameter/get-target-sources',
  TargetDefinitionListGetByFilter = 'Target/get-by-filter',
  TargetDefinitionListGetExcelFile = 'Target/get-list-excel',
  CopyTarget = 'Approve/copy-target',
  GetTargetDetail = 'Target/get',
  TargetDefinitionAdd = 'Target/add',
  TargetDefinitionUpdate = 'Target/update',
  TargetSourceGetInsertForm = 'TargetDetail/get-insert-form',
  TargetSourceGetUpdateForm = 'TargetDetail/get-update-form',
  TargetSourceAdd = 'TargetDetail/add',
  TargetSourceUpdate = 'TargetDetail/update',
}
